### ISSUE TITLE
Docker on CentOS

### ISSUE THREAD

**Issue by davidw-cn** [ryotayamanaka/oracle-pg#12]
Hi Ryota,

I'm working on the Dockers on CentOS, there is no apt commond, I got "apt not installed" error when I exe "docker-compose up" at the final step. Is there any way out?

thanks!

David

**Comment by davidw-cn** [comment]
Hi Ryota,

The result is after my running the final  "docker-compose up" , I got a lot error reports in the zeppelin and Jupyter dockers installation, and graph server docker screen show stoped at "INFO: Starting ProtocolHandler ["http-nio-7007"]". I can access the login page of http://localhost:7007/ui/, but cannot login after I input username and password, it seems graph server  is not properly started. How can I trouble shoot it? 
![image](https://user-images.githubusercontent.com/74531745/99406501-e73e9100-2928-11eb-9114-51fff392a464.png)

My environment is Win10 laptop，installed Oracle vagrant ol7 linux virtualbox with docker engine inside.

Thanks!

David

**Comment by ryotayamanaka** [comment]
Thank you for your feedback!

Since this version (20.4), enabling TLS is mandatory, but my repository is not yet reflected. (I am sorry.)

Could you try accessing http://localhost:7007/ui/ **with Firefox** and check if you can login?

**Comment by davidw-cn** [comment]
Wow, it works!

Thanks Ryota!
