### ISSUE TITLE
AttributeError: module 'pypgx' has no attribute 'get_session'

### ISSUE THREAD

**Issue by jingangliang** [ryotayamanaka/oracle-pg#15]
When I run the code:

`session = pypgx.get_session(base_url=base_url, token=generateToken())
`
the result is:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-06749105faee> in <module>
----> 1 session = pypgx.get_session(base_url=base_url, token=generateToken())

AttributeError: module 'pypgx' has no attribute 'get_session'
```

**Comment by ryotayamanaka** [comment]
It seems `pypgx` is not properly imported.

In the original script [here](https://github.com/ryotayamanaka/oracle-pg/blob/20.4/jupyter/work/customer_360.ipynb),

    import pypgx as pgx

Is there any specific reason, you used the original name `pypgx` by the way?

**Comment by jingangliang** [comment]
This is the full code:

`
import json
import os
import platform
import sys
from urllib.request import Request, urlopen
from urllib.error import HTTPError
import ssl
import pypgx as pgx

ssl._create_default_https_context = ssl._create_unverified_context
base_url = "https://********:7007"
username = "customer_360"
password = "*********"

def generateToken():
    body = json.dumps({ 'username': username, 'password': password }).encode('utf8')
    headers = { 'content-type': 'application/json' }
    request = Request(base_url + '/auth/token', data=body, headers=headers)
    try:
        response = urlopen(request).read().decode('utf-8')
        return json.loads(response).get('access_token')
    except HTTPError as err:
        if err.code == 400:
            print('Authentication failed no username/password given')
        elif err.code == 401:
            print('Authentication failed invalid username/password')
        else:
            print("Server returned HTTP response code: {} for URL: {}".format(err.code, err.url))
        os._exit(1)
        
session = pypgx.get_session(base_url=base_url, token=generateToken()) 
`

The result:
`
AttributeError                            Traceback (most recent call last)
<ipython-input-21-136286eb85d4> in <module>
     29         os._exit(1)
     30 
---> 31 session = pypgx.get_session(base_url=base_url, token=generateToken())

AttributeError: module 'pypgx' has no attribute 'get_session'
`

**Comment by ryotayamanaka** [comment]
Are you getting this error on the docker setup guided in this repository?

**Comment by jingangliang** [comment]
I create a VM from marketplace following this lab([ learning-library](https://oracle.github.io/learning-library/data-management-library/database/graph/graph-server-client/deploy-oci-marketplace-image/workshops/freetier/) ). 
The code in "Lab 6 :Create the Graph" works well.
The "Lab 8 :Graph Visualization" works well.
I successfully run  `pip install pypgx` in OCI Data Science session; after that when I run the code above in a notebook, the error  
`module 'pypgx' has no attribute 'get_session' `occur.

**Comment by jingangliang** [comment]
I think I know the problem. There is a package named "pypgx", which is not oracle pgx python lib.
How can I use the right lib in my own Data Science?

**Comment by jingangliang** [comment]
The problem is solved. I install the Graph Client, and replace `"enable_tls": true`, with `"enable_tls": false`.
It works fine in Jupyter notebook.
But  can't open "Graph Visulization" in my web browser, because of the  `"enable_tls": false` config 😐
