### ISSUE TITLE
Configuring Property Graph in OracleDB container: File does not exist

### ISSUE THREAD

**Issue by nakumgaurav** [ryotayamanaka/oracle-pg#2]
Hi,

the command to configure the property graph:

`@/home/oracle/scripts/oracle-graph-plsql/19c_and_above/catopg.sql`

throws the error:

`SP2-0310: unable to open file "/home/oracle/scripts/oracle-graph-plsql/19c_and_above/catopg.sql"`

I logged into the container using `docker exec -it /bin/bash`, I found that the `/home/oracle/scripts` directory contains only 1 file: `create_users.sql` . Could you please update the instructions to configure the property graph? Thanks!

**Comment by ryotayamanaka** [comment]
You need to run `packages/extract.sh` to create `scripts/oracle-graph-plsql` directory and its contents. Thanks!

**Comment by nakumgaurav** [comment]
Thanks Ryota, that worked!
