### ISSUE TITLE
Error on running the command for data loading from CSV file

### ISSUE THREAD

**Issue by nakumgaurav** [ryotayamanaka/oracle-pg#4]
Hi @ryotayamanaka , I am trying out this tutorial but I am getting an error on running the command for data loading from CSV file:

`sqlldr online_retail/Welcome1@orclpdb1 sqlldr.ctl sqlldr.log sqlldr.bad direct=true`

The error is: `SQL*Loader-522: lfiopn failed for file (sqlldr.log)`

Looks like some permission issue [as per stackoverflow](https://stackoverflow.com/questions/30348567/sqlloader-522-lfiopn-failed-for-file)

Error screenshot:
![Screenshot from 2020-09-07 01-38-57](https://user-images.githubusercontent.com/22325652/92368173-3c9a2e80-f0ac-11ea-9405-0e4e054247a6.png)

P.S.: I have the graph server, client and oracle-db running using `docker compose-up `command

Thanks!

**Comment by ryotayamanaka** [comment]
Thank you!

I added the user ID (oracle = 54321) for running the shell to run the loading:

https://github.com/ryotayamanaka/oracle-pg/blob/master/graphs/online_retail/README.md

```
$ cd oracle-pg/
$ docker-compose exec --user 54321 oracle-db /bin/bash
```
